### ISSUE TITLE
Documentation and comments

### ISSUE THREAD

**Issue by jeremynoesen** [Oribuin/JDACommandHandler#1]
This could also apply to your other public works, but it would be a good idea to create documentation for your code so anyone using your APIs can fully understand how to use it and what everything is for. Please do not take this as negative feedback, I strongly believe it would benefit your code and make it look more professional!

In IntelliJ, you can press alt + enter and select "Add JavaDoc" for methods, instance variables, and classes.

**Comment by Oribuin** [comment]
I don't particularly want to comment absolutely everything because that gets obnoxious to read and work with, I'll comment stuff more but I'm not going to just fill every class with comments since most people can understand it easily.

JavaDocs aren't really necessary honestly as this code is purely meant to be copied into anyone's code and adapted.
